X

diff --git a/.bin/fzf-file-previewer b/.bin/fzf-file-previewer
--- a/.bin/fzf-file-previewer
+++ b/.bin/fzf-file-previewer
@@ -1,193 +1,194 @@
 #!/usr/bin/env sh
-# vim:ft=sh:et:ts=4:sw=4:sts=4:
 
 has() {
-    command -v "$1" >/dev/null 2>&1
+  command -v "$1" >/dev/null 2>&1
 }
 
 which_exe() {
-    # $@: list of commands to test
-    for cmd in "$@"; do
-        if has "$cmd"; then
-            echo "$cmd"
-            return
-        fi
-    done
+  # $@: list of commands to test
+  for cmd in "$@"; do
+    if has "$cmd"; then
+      echo "$cmd"
+      return
+    fi
+  done
 }
 
 fzf_file_previewer() {
-    # $1: file to preview
+  # $1: file to preview
 
-    # In case that the file name starts with a hyphen
-    # and command does not support '--' convention
-    fpath=$(realpath -- "$1" 2>/dev/null)
+  # In case that the file name starts with a hyphen
+  # and command does not support '--' convention
+  fpath=$(realpath -- "$1" 2>/dev/null)
 
-    if [ ! -r "$1" ]; then
-        printf "\033[1m%s\033[0m\n" "File not readable:" >&2
-        printf "%s\n" "$1" >&2
-        return 1
+  if [ ! -r "$1" ]; then
+    printf "\033[1m%s\033[0m\n" "File not readable:" >&2
+    printf "%s\n" "$1" >&2
+    return 1
+  fi
+
+  # Clear possible ueberzugpp image preview
+  if [ -S "$UB_SOCK" ] && has ueberzugpp; then
+    ueberzugpp cmd -s "$UB_SOCK" -a remove -i fzf-file-preview-ub 2>/dev/null
+  fi
+
+  # Preview directories
+  if [ -d "$1" ]; then
+    if has tree; then
+      tree_output=$(tree -N -L 4 -C -- "$1")
+      info=$(echo "$tree_output" | tail -n 1)
+      printf "\033[1m%s\033[0m\n\n" "$info"
+      printf "%s\n" "$tree_output" | tail -n +2
+    else
+      if has find && has wc; then
+        num_files=$(find "$fpath" -type f | wc -l)
+        num_dirs=$(find "$fpath" -type d | wc -l)
+        printf "\033[1m%d directories, %d files\033[0m\n" \
+          "$num_dirs" "$num_files"
+      fi
+      ls -l --color=always -- "$1"
     fi
+    return
+  fi
 
-    # Clear possible ueberzugpp image preview
-    if [ -S "$UB_SOCK" ] && has ueberzugpp; then
-        ueberzugpp cmd -s "$UB_SOCK" -a remove -i fzf-file-preview-ub 2>/dev/null
-    fi
-
-    # Preview directories
-    if [ -d "$1" ]; then
-        if has tree; then
-            tree_output=$(tree -N -L 4 -C -- "$1")
-            info=$(echo "$tree_output" | tail -n 1)
-            printf "\033[1m%s\033[0m\n\n" "$info"
-            printf "%s\n" "$tree_output" | tail -n +2
-        else
-            if has find && has wc; then
-                num_files=$(find "$fpath" -type f | wc -l)
-                num_dirs=$(find "$fpath" -type d | wc -l)
-                printf "\033[1m%d directories, %d files\033[0m\n" \
-                    "$num_dirs" "$num_files"
-            fi
-            ls -l --color=always -- "$1"
+  # Preview regular files
+  if [ -f "$1" ]; then
+    case "$(file -b --mime -- "$1")" in
+      image/*)
+        # ueberzugpp is up and fzf is called from wrapper
+        if [ -S "$UB_SOCK" ] && has ueberzugpp; then
+          if [ "$((FZF_MARGIN_RIGHT + FZF_MARGIN_LEFT + \
+            FZF_PADDING_RIGHT + FZF_PADDING_LEFT))"         -lt \
+            "$FZF_TERM_COLUMNS" ]; then
+          if [ "$FZF_PREVIEW_ORIENTATION" = 'right' ]; then
+            ub_x=$((FZF_TERM_COLUMNS - FZF_PREVIEW_COLUMNS - \
+              FZF_MARGIN_RIGHT - FZF_PADDING_RIGHT - 2))
+          else
+            ub_x=$((FZF_MARGIN_LEFT + FZF_PADDING_LEFT + 2))
+          fi
+          fi
+          if [ "$((FZF_MARGIN_UP + FZF_MARGIN_BOTTOM + \
+            FZF_PADDING_UP + FZF_PADDING_BOTTOM))"         -lt \
+            "$FZF_TERM_LINES" ]; then
+          if [ "$FZF_PREVIEW_ORIENTATION" = 'up' ]; then
+            ub_y=$((FZF_TERM_LINES - FZF_HEIGHT + \
+              FZF_MARGIN_TOP + FZF_PADDING_TOP + 1))
+          else
+            ub_y=$((FZF_TERM_LINES - FZF_MARGIN_BOTTOM - \
+              FZF_PADDING_BOTTOM - FZF_PREVIEW_LINES - 1))
+          fi
+          fi
+          if [ -n "$ub_x" ] && [ -n "$ub_y" ]; then
+            ueberzugpp cmd \
+              -s "$UB_SOCK" \
+              -i fzf-file-preview-ub \
+              -a add \
+              -x "$ub_x" \
+              -y "$ub_y" \
+              --max-width "$FZF_PREVIEW_COLUMNS" \
+              --max-height "$((FZF_PREVIEW_LINES - 1))" \
+              -f "$1" 2>/dev/null
+            return
+          fi
         fi
-        return
-    fi
 
-    # Preview regular files
-    if [ -f "$1" ]; then
-        case "$(file -b --mime -- "$1")" in
-        image/*)
-            # ueberzugpp is up and fzf is called from wrapper
-            if [ -S "$UB_SOCK" ] && has ueberzugpp; then
-                if [ "$((FZF_MARGIN_RIGHT + FZF_MARGIN_LEFT + \
-                FZF_PADDING_RIGHT + FZF_PADDING_LEFT))" -lt \
-                    "$FZF_TERM_COLUMNS" ]; then
-                    if [ "$FZF_PREVIEW_ORIENTATION" = 'right' ]; then
-                        ub_x=$((FZF_TERM_COLUMNS - FZF_PREVIEW_COLUMNS - \
-                            FZF_MARGIN_RIGHT - FZF_PADDING_RIGHT - 2))
-                    else
-                        ub_x=$((FZF_MARGIN_LEFT + FZF_PADDING_LEFT + 2))
-                    fi
-                fi
-                if [ "$((FZF_MARGIN_UP + FZF_MARGIN_BOTTOM + \
-                FZF_PADDING_UP + FZF_PADDING_BOTTOM))" -lt \
-                    "$FZF_TERM_LINES" ]; then
-                    if [ "$FZF_PREVIEW_ORIENTATION" = 'up' ]; then
-                        ub_y=$((FZF_TERM_LINES - FZF_HEIGHT + \
-                            FZF_MARGIN_TOP + FZF_PADDING_TOP + 1))
-                    else
-                        ub_y=$((FZF_TERM_LINES - FZF_MARGIN_BOTTOM - \
-                            FZF_PADDING_BOTTOM - FZF_PREVIEW_LINES - 1))
-                    fi
-                fi
-                if [ -n "$ub_x" ] && [ -n "$ub_y" ]; then
-                    ueberzugpp cmd \
-                        -s "$UB_SOCK" \
-                        -i fzf-file-preview-ub \
-                        -a add \
-                        -x "$ub_x" \
-                        -y "$ub_y" \
-                        --max-width "$FZF_PREVIEW_COLUMNS" \
-                        --max-height "$((FZF_PREVIEW_LINES - 1))" \
-                        -f "$1" 2>/dev/null
-                    return
-                fi
-            fi
-
-            # Use ASCII image previewers if ueberzugpp not available
-            case "$(which_exe chafa imgcat tiv)" in
-            chafa)
-                chafa -f symbols \
-                    -s "$FZF_PREVIEW_COLUMNS"x"$FZF_PREVIEW_LINES" "$fpath"
-                ;;
-            imgcat)
-                imgcat -H -w "$FZF_PREVIEW_COLUMNS" \
-                    -r "$FZF_PREVIEW_LINES" "$fpath"
-                ;;
-            tiv)
-                tiv -w "$FZF_PREVIEW_COLUMNS" -h "$FZF_PREVIEW_LINES" "$fpath"
-                ;;
-            *)
-                echo "No ascii image previewer found, install chafa, imgcat or tiv" >&2
-                ;;
-            esac
+        # Use ASCII image previewers if ueberzugpp not available
+        case "$(which_exe chafa imgcat tiv)" in
+          chafa)
+            chafa -f symbols \
+              -s "$FZF_PREVIEW_COLUMNS"x"$FZF_PREVIEW_LINES" "$fpath"
             ;;
-
-        application/pdf*)
-            if has pdftotext; then
-                pdftotext -l 10 -nopgbrk -nodiag -q "$1" -
-                return
-            else
-                echo 'pdftotext not found' >&2
-            fi
+          imgcat)
+            imgcat -H -w "$FZF_PREVIEW_COLUMNS" \
+              -r "$FZF_PREVIEW_LINES" "$fpath"
             ;;
-
-        application/zip*)
-            if has unzip; then
-                unzip -l "$fpath"
-            elif has zip; then
-                zip -sf -- "$1"
-            else
-                echo 'unzip and zip not found' >&2
-            fi
+          tiv)
+            tiv -w "$FZF_PREVIEW_COLUMNS" -h "$FZF_PREVIEW_LINES" "$fpath"
             ;;
-
-        application/x-tar* | application/gzip*)
-            if has tar; then
-                tar --ignore-command-error -tf "$1" 2>/dev/null
-            else
-                echo 'tar not found' >&2
-            fi
+          *)
+            echo "No ascii image previewer found, install chafa, imgcat or tiv" >&2
             ;;
+        esac
+        ;;
 
-        text/html*)
-            if has w3m; then
-                w3m -dump "$fpath"
-                return
-            elif has html2text; then
-                html2text -- "$1"
-                return
-            fi
-            ;;
+      application/pdf*)
+        if has pdftotext; then
+          pdftotext -l 10 -nopgbrk -nodiag -q "$1" -
+          return
+        else
+          echo 'pdftotext not found' >&2
+        fi
+        ;;
 
-        *)
-            # Use glow for markdown files
-            case "$1" in
-            *.md)
-                if has glow; then
-                    glow -w="$FZF_PREVIEW_COLUMNS" -- "$1"
-                    return
-                fi
-                ;;
-            esac
+      application/zip*)
+        if has unzip; then
+          unzip -l "$fpath"
+        elif     has zip; then
+          zip -sf -- "$1"
+        else
+          echo 'unzip and zip not found' >&2
+        fi
+        ;;
 
-            # Use bat, highlight or cat for remaining files
-            if has bat; then
-                if [ -z "$2" ]; then
-                    bat --theme ansi --paging never --style plain --color always "$1"
-                else
-                    bat --theme ansi --paging never --style numbers --color always "$1" \
-                        --highlight-line "$2"
-                fi
-                return
-            fi
+      application/x-tar* | application/gzip*)
+        if has tar; then
+          tar --ignore-command-error -tf "$1" 2>/dev/null
+        else
+          echo 'tar not found' >&2
+        fi
+        ;;
 
-            if has highlight; then
-                highlight_config="$HOME/.highlight/themes/highlight.theme"
-                if [ ! -e "$highlight_config" ]; then
-                    highlight -O ansi --force -- "$1"
-                else
-                    highlight -O ansi --force --config-file "$highlight_config" -- "$1"
-                fi
-                return
-            fi
+      text/html*)
+        if has w3m; then
+          w3m -dump "$fpath"
+          return
+        elif     has html2text; then
+          html2text -- "$1"
+          return
+        fi
+        ;;
 
-            if has cat; then
-                cat "$1"
-                return
+      *)
+        # Use glow for markdown files
+        case "$1" in
+          *.md)
+            if has glow; then
+              glow -w="$FZF_PREVIEW_COLUMNS" -- "$1"
+              return
             fi
             ;;
         esac
-    fi
+
+        # Use bat, highlight or cat for remaining files
+        if has bat; then
+          if [ -z "$2" ]; then
+            bat --theme ansi --paging never --style plain --color always "$1"
+          else
+            bat --theme ansi --paging never --style numbers --color always "$1" \
+              --highlight-line "$2"
+          fi
+          return
+        fi
+
+        if has highlight; then
+          highlight_config="$HOME/.highlight/themes/highlight.theme"
+          if [ ! -e "$highlight_config" ]; then
+            highlight -O ansi --force -- "$1"
+          else
+            highlight -O ansi --force --config-file "$highlight_config" -- "$1"
+          fi
+          return
+        fi
+
+        if has cat; then
+          cat "$1"
+          return
+        fi
+        ;;
+    esac
+  fi
 }
 
 fzf_file_previewer "$@"
+
+# vim:ft=sh:ts=2:sw=2:et:
diff --git a/.bin/mb b/.bin/mb
--- a/.bin/mb
+++ b/.bin/mb
@@ -1,15 +1,13 @@
 #!/usr/bin/env sh
-# vim: ft=sh ts=4 sw=4 sts=4 et :
-# Make a backup for a file or directory
 
 print_help() {
-    script_name=$(basename "$0")
-    cat <<EOF
-${script_name} - make backup
-Usage: ${script_name} [options] <file>
-       ${script_name} -R [options] <file.bak>
+  script_name=$(basename "$0")
+  cat <<EOF
+  ${script_name} - make backup
+  Usage: ${script_name} [options] <file>
+  ${script_name} -R [options] <file.bak>
 
-Options:
+  Options:
   -h, --help    Show this help message
   -m, --move    Use move instead of copy (both backup and restore)
   -R, --restore Restore from backup
@@ -18,106 +16,108 @@ EOF
 
 # Remove trailing slashes from path
 clean_path() {
-    while [ "${1%/}" != "$1" ]; do
-        set -- "${1%/}"
-    done
-    printf '%s\n' "$1"
+  while [ "${1%/}" != "$1" ]; do
+    set -- "${1%/}"
+  done
+  printf '%s\n' "$1"
 }
 
 backup() {
-    src="$1"
-    bak="$2"
+  src="$1"
+  bak="$2"
 
-    if [ ! -e "$src" ]; then
-        echo "'$src' does not exist" >&2
-        return 1
-    fi
-    if [ -e "$bak" ]; then
-        echo "'$bak' already exists" >&2
-        return 1
-    fi
+  if [ ! -e "$src" ]; then
+    echo "'$src' does not exist" >&2
+    return 1
+  fi
+  if [ -e "$bak" ]; then
+    echo "'$bak' already exists" >&2
+    return 1
+  fi
 
-    if [ "$move_flag" -eq 1 ]; then
-        if ! mv "$src" "$bak"; then
-            echo "Failed to move '$src' to '$bak'" >&2
-            return 1
-        fi
-    else
-        if ! cp -LR "$src" "$bak"; then
-            echo "Failed to create backup copy" >&2
-            return 1
-        fi
+  if [ "$move_flag" -eq 1 ]; then
+    if ! mv "$src" "$bak"; then
+      echo "Failed to move '$src' to '$bak'" >&2
+      return 1
     fi
+  else
+    if ! cp -LR "$src" "$bak"; then
+      echo "Failed to create backup copy" >&2
+      return 1
+    fi
+  fi
 }
 
 restore() {
-    src_bak="$1"
-    original="$2"
+  src_bak="$1"
+  original="$2"
 
-    if [ ! -e "$src_bak" ]; then
-        echo "'$src_bak' does not exist" >&2
-        return 1
-    fi
-    if [ -e "$original" ]; then
-        echo "'$original' already exists" >&2
-        return 1
-    fi
+  if [ ! -e "$src_bak" ]; then
+    echo "'$src_bak' does not exist" >&2
+    return 1
+  fi
+  if [ -e "$original" ]; then
+    echo "'$original' already exists" >&2
+    return 1
+  fi
 
-    if [ "$move_flag" -eq 1 ]; then
-        if ! mv "$src_bak" "$original"; then
-            echo "Failed to restore by moving '$src_bak' to '$original'" >&2
-            return 1
-        fi
-    else
-        if ! cp -LR "$src_bak" "$original"; then
-            echo "Failed to restore by copying '$src_bak' to '$original'" >&2
-            return 1
-        fi
+  if [ "$move_flag" -eq 1 ]; then
+    if ! mv "$src_bak" "$original"; then
+      echo "Failed to restore by moving '$src_bak' to '$original'" >&2
+      return 1
     fi
+  else
+    if ! cp -LR "$src_bak" "$original"; then
+      echo "Failed to restore by copying '$src_bak' to '$original'" >&2
+      return 1
+    fi
+  fi
 }
 
 main() {
-    move_flag=0
-    restore_flag=0
+  move_flag=0
+  restore_flag=0
 
-    while [ $# -gt 0 ]; do
-        case "$1" in
-        -m | --move)
-            move_flag=1
-            shift
-            ;;
-        -R | --restore)
-            restore_flag=1
-            shift
-            ;;
-        -h | --help)
-            print_help
-            return 0
-            ;;
-        *)
-            break
-            ;;
-        esac
-    done
-
-    if [ $# -ne 1 ]; then
-        echo "Error: Exactly one file argument required" >&2
+  while [ $# -gt 0 ]; do
+    case "$1" in
+      -m | --move)
+        move_flag=1
+        shift
+        ;;
+      -R | --restore)
+        restore_flag=1
+        shift
+        ;;
+      -h | --help)
         print_help
-        return 1
-    fi
+        return 0
+        ;;
+      *)
+        break
+        ;;
+    esac
+  done
 
-    if [ "$restore_flag" -eq 1 ]; then
-        src_bak="$1"
-        if [ "${src_bak%.bak}" = "$src_bak" ]; then
-            echo "Restore requires a .bak file" >&2
-            return 1
-        fi
-        restore "$src_bak" "${src_bak%.bak}"
-    else
-        src="$1"
-        bak="$(clean_path "$src").bak"
-        backup "$src" "$bak"
+  if [ $# -ne 1 ]; then
+    echo "Error: Exactly one file argument required" >&2
+    print_help
+    return 1
+  fi
+
+  if [ "$restore_flag" -eq 1 ]; then
+    src_bak="$1"
+    if [ "${src_bak%.bak}" = "$src_bak" ]; then
+      echo "Restore requires a .bak file" >&2
+      return 1
     fi
+    restore "$src_bak" "${src_bak%.bak}"
+  else
+    src="$1"
+    bak="$(clean_path "$src").bak"
+    backup "$src" "$bak"
+  fi
 }
 
 main "$@"
+
+# vim:ft=sh:ts=2:sw=2:et:
diff --git a/.bin/md2html b/.bin/md2html
--- a/.bin/md2html
+++ b/.bin/md2html
@@ -1,38 +1,39 @@
 #!/usr/bin/env sh
-# vim:ft=sh:et:ts=4:sw=4:sts=4:
 
 md2html() {
-    pandoc \
-        --katex \
-        --standalone \
-        --embed-resources \
-        -f markdown-implicit_figures \
-        --css ~/.config/pandoc/css/paper.css \
-        -t html \
-        "$1" \
-        -o "${1%.md}.html"
-}
+  pandoc \
+    --katex \
+    --standalone \
+    --embed-resources \
+    -f markdown-implicit_figures \
+    --css ~/.config/pandoc/css/paper.css \
+    -t html \
+    "$1" \
+    -o "${1%.md}.html"
+  }
 
 main() {
-    rc=0
+  rc=0
 
-    for file in "$@"; do
-        oldpwd=$PWD
+  for file in "$@"; do
+    oldpwd=$PWD
 
-        # Pictures in markdown cannot be fetched if we are not in the same
-        # directory
-        cd "$(dirname "$(realpath "$file")")" || return
+    # Pictures in markdown cannot be fetched if we are not in the same
+    # directory
+    cd "$(dirname "$(realpath "$file")")" || return
 
-        if ! md2html "$(basename "$file")"; then
-            echo "md2html: error: pandoc failed to convert '$file'" >&2
-            cd "$oldpwd" || return
-            rc=1
-        fi
+    if ! md2html "$(basename "$file")"; then
+      echo "md2html: error: pandoc failed to convert '$file'" >&2
+      cd "$oldpwd" || return
+      rc=1
+    fi
 
-        cd "$oldpwd" || return
-    done
+    cd "$oldpwd" || return
+  done
 
-    return "$rc"
+  return "$rc"
 }
 
 main "$@"
+
+# vim:ft=sh:ts=2:sw=2:et:
diff --git a/.bin/md2tex b/.bin/md2tex
--- a/.bin/md2tex
+++ b/.bin/md2tex
@@ -1,42 +1,43 @@
 #!/usr/bin/env sh
-# vim:ft=sh:et:ts=4:sw=4:sts=4:
 
 md2tex() {
-    pandoc \
-        --standalone \
-        -f markdown-implicit_figures \
-        -t latex \
-        "$1" \
-        -o "${1%.md}.tex"
-}
+  pandoc \
+    --standalone \
+    -f markdown-implicit_figures \
+    -t latex \
+    "$1" \
+    -o "${1%.md}.tex"
+  }
 
 main() {
-    if [ $# -eq 0 ]; then
-        echo "Error: no input files" >&2
-        printf "Usage: %s files...\n" "$(basename "$0")" >&2
-        return 1
+  if [ $# -eq 0 ]; then
+    echo "Error: no input files" >&2
+    printf "Usage: %s files...\n" "$(basename "$0")" >&2
+    return 1
+  fi
+
+  rc=0
+
+  for file in "$@"; do
+    oldpwd=$PWD
+
+    # Pictures in markdown cannot be fetched if we are not in the same
+    # directory
+    cd "$(dirname "$(realpath "$file")")" || return
+
+    if ! md2tex "$(basename "$file")"; then
+      rc=$?
+      echo "md2tex: error: pandoc failed to convert '$file' with exit code $rc" >&2
+      cd "$oldpwd" || return
+      rc=1
     fi
 
-    rc=0
+    cd "$oldpwd" || return
+  done
 
-    for file in "$@"; do
-        oldpwd=$PWD
-
-        # Pictures in markdown cannot be fetched if we are not in the same
-        # directory
-        cd "$(dirname "$(realpath "$file")")" || return
-
-        if ! md2tex "$(basename "$file")"; then
-            rc=$?
-            echo "md2tex: error: pandoc failed to convert '$file' with exit code $rc" >&2
-            cd "$oldpwd" || return
-            rc=1
-        fi
-
-        cd "$oldpwd" || return
-    done
-
-    return "$rc"
+  return "$rc"
 }
 
 main "$@"
+
+# vim:ft=sh:ts=2:sw=2:et:
diff --git a/.bin/of b/.bin/of
--- a/.bin/of
+++ b/.bin/of
@@ -1,53 +1,54 @@
 #!/usr/bin/env sh
-# vim: ft=sh ts=4 sw=4 sts=4 et :
 
 has() {
-    command -v "$1" >/dev/null 2>&1
+  command -v "$1" >/dev/null 2>&1
 }
 
 # Open a file using $EDITOR or xdg-open
 of() {
-    # $@: files to open
-    if ! has file >/dev/null 2>&1; then
-        echo "file executable not found" >&2
-        return 1
+  # $@: files to open
+  if ! has file >/dev/null 2>&1; then
+    echo "file executable not found" >&2
+    return 1
+  fi
+
+  trap 'rm -f "$text_files" "$other_files"' EXIT INT TERM HUP
+
+  # Create temporary files to store file lists
+  text_files=$(mktemp)
+  other_files=$(mktemp)
+
+  # Categorize files based on their type
+  for file in "$@"; do
+    if file -b "$file" | grep -qE 'text|empty'; then
+      printf '%s\n' "$file" >>"$text_files"
+    else
+      printf '%s\n' "$file" >>"$other_files"
     fi
+  done
 
-    trap 'rm -f "$text_files" "$other_files"' EXIT INT TERM HUP
+  # Handle non-text files with xdg-open
+  if has xdg-open >/dev/null 2>&1; then
+    while read -r file; do
+      detach xdg-open "$file" >/dev/null 2>&1
+    done     <"$other_files"
+  elif   [ -s "$other_files" ]; then
+    echo "xdg-open not found, omit opening files:" >&2
+    cat "$other_files" >&2
+  fi
 
-    # Create temporary files to store file lists
-    text_files=$(mktemp)
-    other_files=$(mktemp)
-
-    # Categorize files based on their type
-    for file in "$@"; do
-        if file -b "$file" | grep -qE 'text|empty'; then
-            printf '%s\n' "$file" >>"$text_files"
-        else
-            printf '%s\n' "$file" >>"$other_files"
-        fi
-    done
-
-    # Handle non-text files with xdg-open
-    if has xdg-open >/dev/null 2>&1; then
-        while read -r file; do
-            detach xdg-open "$file" >/dev/null 2>&1
-        done <"$other_files"
-    elif [ -s "$other_files" ]; then
-        echo "xdg-open not found, omit opening files:" >&2
-        cat "$other_files" >&2
+  # Handle text files with $EDITOR
+  if [ -s "$text_files" ]; then
+    if has "$EDITOR" >/dev/null 2>&1; then
+      # Use xargs to handle multiple files
+      xargs "$EDITOR" <"$text_files"
+    else
+      echo "\$EDITOR not found, omit opening files:" >&2
+      cat "$text_files" >&2
     fi
-
-    # Handle text files with $EDITOR
-    if [ -s "$text_files" ]; then
-        if has "$EDITOR" >/dev/null 2>&1; then
-            # Use xargs to handle multiple files
-            xargs "$EDITOR" <"$text_files"
-        else
-            echo "\$EDITOR not found, omit opening files:" >&2
-            cat "$text_files" >&2
-        fi
-    fi
+  fi
 }
 
 of "$@"
+
+# vim:ft=sh:ts=2:sw=2:et:
diff --git a/.bin/setfont b/.bin/setfont
--- a/.bin/setfont
+++ b/.bin/setfont
@@ -6,116 +6,116 @@ FONT_IN_USE=$(sed 's/font-family = "\(.*\)"/\1/g' <"$CONFIGURATIONS"/ghostty/con
 
 FONTS_AVAILABLE=()
 while IFS= read -r font; do
-    FONTS_AVAILABLE+=("$font")
+  FONTS_AVAILABLE+=("$font")
 done < <(ghostty +list-fonts | grep -v '^[[:blank:]]' | grep -v '^$' | sort | uniq)
 
 switch_alacritty() {
-    (
-        ALACRITTY_CONFIGURATION="$CONFIGURATIONS/alacritty/local.toml"
+  (   
+    ALACRITTY_CONFIGURATION="$CONFIGURATIONS/alacritty/local.toml"
 
-        if [ ! -f "$ALACRITTY_CONFIGURATION" ]; then
-            echo "[font.normal]" >"$ALACRITTY_CONFIGURATION"
-            echo "family = '$FONT'" >>"$ALACRITTY_CONFIGURATION"
-        else
-            sed -i "s|^\([[:space:]]*\)family = .*|\1family = '$FONT'|" "$ALACRITTY_CONFIGURATION"
-        fi
+    if [ ! -f "$ALACRITTY_CONFIGURATION" ]; then
+      echo "[font.normal]" >"$ALACRITTY_CONFIGURATION"
+      echo "family = '$FONT'" >>"$ALACRITTY_CONFIGURATION"
+    else
+      sed -i "s|^\([[:space:]]*\)family = .*|\1family = '$FONT'|" "$ALACRITTY_CONFIGURATION"
+    fi
 
-        touch "$CONFIGURATIONS/alacritty/alacritty.toml"
-    )
+    touch "$CONFIGURATIONS/alacritty/alacritty.toml"
+  )
 }
 
 switch_ghostty() {
-    (
-        GHOSTTY_CONFIGURATION="$CONFIGURATIONS/ghostty/config.local"
+  (   
+    GHOSTTY_CONFIGURATION="$CONFIGURATIONS/ghostty/config.local"
 
-        if [ ! -f "$GHOSTTY_CONFIGURATION" ]; then
-            echo "font-family = \"$FONT\"" >"$GHOSTTY_CONFIGURATION"
-        else
-            sed -i "s|^font-family = .*|font-family = \"$FONT\"|" "$GHOSTTY_CONFIGURATION"
-        fi
+    if [ ! -f "$GHOSTTY_CONFIGURATION" ]; then
+      echo "font-family = \"$FONT\"" >"$GHOSTTY_CONFIGURATION"
+    else
+      sed -i "s|^font-family = .*|font-family = \"$FONT\"|" "$GHOSTTY_CONFIGURATION"
+    fi
 
-        kill -USR2 "$(pgrep ghostty)"
-    )
+    kill -USR2 "$(pgrep ghostty)"
+  )
 }
 
 usage() {
-    local program
-    program=$(basename "$0")
-    echo "Usage: $program <font_name>"
-    echo
-    echo "       -h,--help    Display this message"
-    echo "       -l,--list    List all the available fonts"
+  local program
+  program=$(basename "$0")
+  echo "Usage: $program <font_name>"
+  echo
+  echo "       -h,--help    Display this message"
+  echo "       -l,--list    List all the available fonts"
 }
 
 list_fonts() {
-    echo "Available fonts:"
-    for font in "${FONTS_AVAILABLE[@]}"; do
-        if [ "$font" = "$FONT_IN_USE" ]; then
-            printf "  \033[4m%s\033[0m (current)\n" "$font"
-        else
-            printf "  %s\n" "$font"
-        fi
-    done
+  echo "Available fonts:"
+  for font in "${FONTS_AVAILABLE[@]}"; do
+    if [ "$font" = "$FONT_IN_USE" ]; then
+      printf "  \033[4m%s\033[0m (current)\n" "$font"
+    else
+      printf "  %s\n" "$font"
+    fi
+  done
 }
 
 main() {
-    while [ $# -gt 0 ]; do
-        case $1 in
-            -h | --help)
-                usage
-                exit 0
-                ;;
-            -l | --list)
-                list_fonts
-                exit 0
-                ;;
-            -*)
-                echo "Unknown option: $1" >&2
-                echo
-                usage >&2
-                exit 1
-                ;;
-            *)
-                break
-                ;;
-        esac
-        shift
-    done
-
-    if [ $# -ne 1 ]; then
-        usage "$@"
+  while [ $# -gt 0 ]; do
+    case $1 in
+      -h | --help)
+        usage
         exit 0
-    fi
-
-    FONT="$1"
-
-    VALID=false
-
-    for avail in "${FONTS_AVAILABLE[@]}"; do
-        if [ "$FONT" = "$avail" ]; then
-            VALID=true
-            break
-        fi
-    done
-
-    if [ "$VALID" = false ]; then
-        echo "Unknown font: $1" >&2
+        ;;
+      -l | --list)
+        list_fonts
+        exit 0
+        ;;
+      -*)
+        echo "Unknown option: $1" >&2
         echo
-        usage "$@"
+        usage >&2
         exit 1
+        ;;
+      *)
+        break
+        ;;
+    esac
+    shift
+  done
+
+  if [ $# -ne 1 ]; then
+    usage "$@"
+    exit 0
+  fi
+
+  FONT="$1"
+
+  VALID=false
+
+  for avail in "${FONTS_AVAILABLE[@]}"; do
+    if [ "$FONT" = "$avail" ]; then
+      VALID=true
+      break
     fi
+  done
 
-    if [ "$FONT" = "$FONT_IN_USE" ]; then
-        echo "I can't handle change O.o"
-        exit 0
-    fi
+  if [ "$VALID" = false ]; then
+    echo "Unknown font: $1" >&2
+    echo
+    usage "$@"
+    exit 1
+  fi
 
-    switch_alacritty
-    switch_ghostty
+  if [ "$FONT" = "$FONT_IN_USE" ]; then
+    echo "I can't handle change O.o"
+    exit 0
+  fi
 
-    printf "Switched to \033[4m%s\033[0m\n" "$FONT"
+  switch_alacritty
+  switch_ghostty
+
+  printf "Switched to \033[4m%s\033[0m\n" "$FONT"
 }
 
 main "$@"
 
-# vim:ft=sh:et:ts=4:sw=4:sts=4:
+# vim:ft=sh:ts=2:sw=2:et:
